<script setup>
import Minus from "@/assets/icons/Minus.vue";
import Plus from "@/assets/icons/Plus.vue";
import { ref } from "vue";
import FAQdog from "@/assets/img/Home/FAQdogMob.png";
import FAQDogs from "@/assets/img/Home/FAQDogs.png";

const FAQcards = [
  {
    title: "What is $DOGEBALL?",
    text: `$DOGEBALL is a dual-utility coin that powers a custom Layer 2 blockchain designed for near zero-fee transactions, high speed, and top-tier security, seamlessly integrated with the $DOGEBALL online game. As the native token, $DOGEBALL fuels the entire ecosystem, offering a robust foundation for users and gamers alike. Tokens have a real-life utility and will be used for completing transactions in the gaming industry in the future.`,
  },
  {
    title: "What is $DOGEBALL staking?",
    text: `Staking $DOGEBALL involves locking your tokens in a secure smart contract for a set period (during presale only) to earn additional $DOGEBALL tokens at no extra cost. Staking rewards will be released following the 7-day minimum vesting period. Refer to the 'STAKING' section in 'HOW TO BUY ABOVE'. <a href="#howToBuy" class="underline">Click Here</a>`,
  },
  {
    title: "How do I buy $DOGEBALL?",
    text: `You can join the $DOGEBALL community by simply connecting your chosen wallet to the presale widget at the top of this page <a href="#presale" class="underline">(Click Here)</a>. Select your preferred crypto currency to use or pay by your Credit/Debit Card to secure your $DOGEBALL tokens.`,
  },
  {
    title: "Where are my $DOGEBALL tokens?",
    text: `Users can see their $DOGEBALL balance once their wallet is connected (see top of the page). The 'Dashboard' section in the presale widget will show the user balance and purchase history. <a href="#presale" class="underline">Click Here</a>`,
  },
  {
    title: "When do I receive my tokens?",
    text: `After purchasing $DOGEBALL in the presale, you can use the same wallet to claim your tokens before the initial exchange listing. Stay tuned to our social media for claim and listing date announcements.`,
  },
  {
    title: "Is $DOGEBALL token safe to buy?",
    text: `Yes, the $DOGEBALL contract has been audited by Coinsult, one of the largest and trusted blockchain project auditors, achieving 100% in the overall audit score. <a href="/DOGEBALLWhitepaper.pdf" target="_blank" class="underline">Click Here</a> for the full audit report. `,
  },
  {
    title: "How do I generate a referral code and use bonus codes?",
    text: `Your unique referral code can be generated by clicking 'Connect Wallet' and clicking 'Dashboard'; each user will be provided with their own unique referral code and URL link to provide to other users. The user being referred should enter this on the 'Buy' screen under the button 'Buy $DOGEBALL' and click 'Apply'. Referral bonus amounts will be added to the purchase amount and visible in the 'Dashboard' (for both referrer and user being referred). Limited time bonus codes should be entered by clicking 'Bonus Code' (under the button 'Buy $DOGEBALL' following wallet connect) and clicking 'Apply'.`,
  },
];

const FAQcardsMob = [
  {
    title: "What is $DOGEBALL?",
    text: `$DOGEBALL is a dual-utility coin that powers a custom Layer 2 blockchain designed for near zero-fee transactions, high speed, and top-tier security, seamlessly integrated with the $DOGEBALL online game. As the native token, $DOGEBALL fuels the entire ecosystem, offering a robust foundation for users and gamers alike. Tokens have a real-life utility and will be used for completing transactions in the gaming industry in the future.`,
  },
  {
    title: "How do I buy $DOGEBALL?",
    text: `You can join the $DOGEBALL community by simply connecting your chosen wallet to the presale widget at the top of this page <a href="#presale" class="underline">(Click Here)</a>. Select your preferred crypto currency to use or pay by your Credit/Debit Card to secure your $DOGEBALL tokens.`,
  },
  {
    title: "What is $DOGEBALL staking?",
    text: `Staking $DOGEBALL involves locking your tokens in a secure smart contract for a set period (during presale only) to earn additional $DOGEBALL tokens at no extra cost. Staking rewards will be released following the 7-day minimum vesting period. Refer to the 'STAKING' section in 'HOW TO BUY ABOVE'. <a href="#howToBuy" class="underline">Click Here</a>`,
  },
  {
    title: "How do I generate a referral code and use bonus codes?",
    text: `Your unique referral code can be generated by clicking 'Connect Wallet' and clicking 'Dashboard'; each user will be provided with their own unique referral code and URL link to provide to other users. The user being referred should enter this on the 'Buy' screen under the button 'Buy $DOGEBALL' and click 'Apply'. Referral bonus amounts will be added to the purchase amount and visible in the 'Dashboard' (for both referrer and user being referred). Limited time bonus codes should be entered by clicking 'Bonus Code' (under the button 'Buy $DOGEBALL' following wallet connect) and clicking 'Apply'.`,
  },
  {
    title: "Where are my $DOGEBALL tokens?",
    text: `Users can see their $DOGEBALL balance once their wallet is connected (see top of the page). The 'Dashboard' section in the presale widget will show the user balance and purchase history. <a href="#presale" class="underline">Click Here</a>`,
  },
  {
    title: "When do I receive my tokens?",
    text: `After purchasing $DOGEBALL in the presale, you can use the same wallet to claim your tokens before the initial exchange listing. Stay tuned to our social media for claim and listing date announcements.`,
  },
  {
    title: "Is $DOGEBALL token safe to buy?",
    text: `Yes, the $DOGEBALL contract has been audited by Coinsult, one of the largest and trusted blockchain project auditors, achieving 100% in the overall audit score. <a href="/DOGEBALLWhitepaper.pdf" target="_blank" class="underline">Click Here</a> for the full audit report. `,
  },
];

const openIndex = ref(null);

function toggleOpen(index) {
  openIndex.value = openIndex.value === index ? null : index;
}

const isMobile = window.innerWidth < 768;
</script>

<template>
  <div
    id="faq"
    class="flex px-5 h-[1000px] max-2xl:!bg-cover bgFill max-lg:h-[950px] max-md:h-max flex-col relative py-20 max-md:py-12 max-md:pb-0 gap-12 bg-[center_bottom] bg-cover bg-no-repeat bg-[url('@/assets/img/Home/FAQBg.png')] overflow-hidden max-md:bg-[url('@/assets/img/Home/FAQBgMob.png')]"
  >
    <div class="title z-20 uppercase max-w-[600px] text-center mx-auto">
      Frequently Asked Questions
    </div>

    <div
      class="w-full max-w-[1600px] max-md:hidden px-5 h-auto absolute bottom-[30px] right-1/2 translate-x-1/2"
    >
      <img :src="FAQDogs" class="object-contain" />
    </div>

    <div class="flex z-30 flex-col gap-4 max-w-7xl mx-auto max-md:h-[640px]">
      <div class="grid grid-cols-2 max-md:grid-cols-1 gap-4">
        <div class="flex flex-col gap-4">
          <div
            v-for="(card, i) in isMobile
              ? FAQcardsMob
              : FAQcards.filter((_, idx) => idx % 2 === 0)"
            :key="isMobile ? i : i * 2"
            class="p-8 max-md:p-4 gap-4 w-full max-w-[450px] backdrop-blur-sm relative bg-[rgba(53,19,147,0.52)] rounded-2xl flex flex-col transition-all"
          >
            <div
              class="absolute inset-0 rounded-2xl"
              style="
                background: linear-gradient(
                  145deg,
                  rgba(255, 255, 255, 0.6) 0%,
                  rgba(255, 255, 255, 0.1) 40%,
                  rgba(255, 255, 255, 0.6) 100%
                );
                -webkit-mask: linear-gradient(#fff 0 0) content-box,
                  linear-gradient(#fff 0 0);
                -webkit-mask-composite: xor;
                mask-composite: exclude;
                padding: 1px;
              "
            ></div>

            <div
              class="flex gap-4 items-start cursor-pointer z-50"
              @click="toggleOpen(isMobile ? i : i * 2)"
            >
              <div
                class="rounded-full h-8 w-8 min-w-[32px] flex items-center bg-[#FFEEE1] justify-center"
              >
                <component
                  :is="openIndex === (isMobile ? i : i * 2) ? Minus : Plus"
                />
              </div>

              <div
                class="text-xl max-md:text-base my-auto font-medium leading-[110%]"
              >
                {{ card.title }}
              </div>
            </div>

            <Transition name="expand">
              <p
                v-if="openIndex === (isMobile ? i : i * 2)"
                v-html="card.text"
                class="text-base max-md:text-sm leading-[120%] font-grotesk font-normal z-50 pl-12 max-md:pl-0"
              />
            </Transition>
          </div>
        </div>

        <div class="flex flex-col gap-4 max-md:hidden">
          <div
            v-for="(card, i) in FAQcards.filter((_, idx) => idx % 2 === 1)"
            :key="i * 2 + 1"
            class="p-8 gap-4 w-full max-w-[450px] backdrop-blur-sm relative bg-[rgba(53,19,147,0.52)] rounded-2xl flex flex-col transition-all"
          >
            <div
              class="absolute inset-0 rounded-2xl"
              style="
                background: linear-gradient(
                  145deg,
                  rgba(255, 255, 255, 0.6) 0%,
                  rgba(255, 255, 255, 0.1) 40%,
                  rgba(255, 255, 255, 0.6) 100%
                );
                -webkit-mask: linear-gradient(#fff 0 0) content-box,
                  linear-gradient(#fff 0 0);
                -webkit-mask-composite: xor;
                mask-composite: exclude;
                padding: 1px;
              "
            ></div>

            <div
              class="flex gap-4 items-start cursor-pointer z-50"
              @click="toggleOpen(i * 2 + 1)"
            >
              <div
                class="rounded-full h-8 w-8 min-w-[32px] flex items-center bg-[#FFEEE1] justify-center"
              >
                <component :is="openIndex === i * 2 + 1 ? Minus : Plus" />
              </div>

              <div class="text-xl my-auto font-medium leading-[110%]">
                {{ card.title }}
              </div>
            </div>

            <Transition name="expand">
              <p
                v-if="openIndex === i * 2 + 1"
                v-html="card.text"
                class="text-base leading-[120%] z-50 pl-12"
              />
            </Transition>
          </div>
        </div>
      </div>
    </div>
    <div class="h-auto w-full mx-auto max-w-[400px] md:hidden">
      <img :src="FAQdog" class="object-contain" />
    </div>
  </div>
</template>

<style scoped>
.expand-enter-active,
.expand-leave-active {
  transition: all 0.3s ease;
  max-height: 500px;
  opacity: 1;
}

.expand-enter-from,
.expand-leave-to {
  max-height: 0;
  opacity: 0;
  overflow: hidden;
}
</style>
